version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/mini_bharat.db:/app/mini_bharat.db
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
  dashboard:
    build: ./backend
    command: bash -c "pip install streamlit && streamlit run dashboard/app.py --server.port 8501 --server.headless true"
    ports:
      - '8501:8501'
    volumes:
      - ./:/app
